name: End to End Testing

on: [pull_request, push]


jobs:
  test:
    strategy:
      matrix:
        include:
        - xcodeVersion: '13.1'
          iosVersion: '15.0'
          deviceName: iPhone 13
        - xcodeVersion: '14.2'
          iosVersion: '16.2'
          deviceName: iPhone 14
    env:
      CI: true
      _FORCE_LOGS: 1
      DEVICE_NAME: ${{ matrix.deviceName }}
      XCODE_VERSION: ${{ matrix.xcodeVersion }}
      IOS_SDK: ${{ matrix.iosVersion }}
    # https://github.com/actions/runner-images/tree/main/images/macos
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        check-latest: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "${{ matrix.xcodeVersion }}"
    - run: xcrun simctl list
      name: List devices on Xcode@${{ matrix.xcodeVersion }}
    - name: Install dependency
      run: |
        pip install pip -U
        pip install -r requirements.txt.lock -U
        pip install -r requirements.dev.txt -U
    - name: Run e2e test
      run: |
        python -m pytest
    